site_name: Berlin United - Documentation

extra_css:
  - stylesheets/extra.css

nav:
  - 'index.md'
  - Teamreport:
    - 'teamreport/index.md'
    - 'teamreport/introduction.md'
    - 'teamreport/architecture_intro.md'
    - 'teamreport/debugging.md'
    - 'teamreport/vision.md'
    - 'teamreport/modeling.md'
    - 'teamreport/motion.md'
    - 'teamreport/behavior.md'
    - 'teamreport/bibliography.md'
  - Tooling:
    - 'naoth_tools/rc.md'
    - 'naoth_tools/naoscp.md'
    - 'naoth_tools/xabsleditor.md'
    - 'naoth_tools/simspark.md'
    - 'naoth_tools/webots.md'
    - 'naoth_tools/gitlab-ci.md'
    - 'naoth_tools/lab-trackingsystem.md'
    - 'robocup_tools/index.md'
    - 'robocup_tools/game_recording.md'
  - Guides:
    - 'guides/onboarding.md'
    - Setup:
        - 'guides/setup/naoth_code_setup.md'
        - 'guides/setup/robot_setup.md'
        - 'guides/setup/nao_config.md'
    - Working With Robots:
        - 'guides/robot_handling.md'
        - 'guides/robots/known-robot-issues.md'
    - 'guides/working-with-logfiles/working-with-logfiles.md'
    - 'guides/working-with-sound/working-with-sound.md'
    - 'guides/logging.md'
    - 'guides/obstacle_detection.md'
    - 'guides/keyframe_motions.md'
    - 'guides/other_teams.md'
    - Code Conventions:
        - 'guides/coding_guidelines.md'
        - 'guides/git-hooks.md'
    - Deep Learning:
        - 'guides/deeplearning/training.md'
        - 'guides/deeplearning/deep_learning_annotation.md'
        - 'guides/deeplearning/deep_learning_deployment.md'

theme:
  name: material
  locale: en
  favicon: img/favicon.ico
  logo: img/favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 3
      
  - attr_list
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - mkdocs-video

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/naoteamhumboldt
    - icon: fontawesome/brands/github
      link: https://github.com/BerlinUnited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/teamhumboldt
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/naoteamhumboldt