site_name: Berlin United - Teamreport
nav:
    - 'index.md'
    - 'introduction.md'
    - 'architecture_intro.md'
    - 'debugging.md'
    - 'vision.md'
    - 'modeling.md'
    - 'motion.md'
    - 'behavior.md'
    - 'bibliography.md'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - proto

plugins:
  - bibtex:
      bib_file: "papers.bib"
      cite_style: "pandoc"
