site_name: Berlin United - Documentation
nav:
  - Teamreport:
    - 'index.md'
    - 'introduction.md'
    - 'architecture_intro.md'
    - 'debugging.md'
    - 'vision.md'
    - 'modeling.md'
    - 'motion.md'
    - 'behavior.md'
    - 'bibliography.md'
  - Tooling:
    - 'naoth_tools/rc.md'
    - 'naoth_tools/naoscp.md'
    - 'naoth_tools/xabsleditor.md'
    - 'naoth_tools/simspark.md'
    - 'naoth_tools/webots.md'
    - 'naoth_tools/gitlab-ci.md'
    - 'naoth_tools/cvat.md'
    - 'naoth_tools/lab-trackingsystem.md'
    - 'robocup_tools/index.md'
    - 'robocup_tools/game_recording.md'
  - Guides:
    - 'guides/onboarding.md'
    - 'guides/naoth_code_setup.md'
    - 'guides/robot_setup.md'
    - 'guides/robot_handling.md'
    - 'guides/logging.md'
    - 'guides/deep_learning_annotation.md'
    - 'guides/deep_learning_training.md'
    - 'guides/deep_learning_deployment.md'
    - 'guides/obstacle_detection.md'
    - 'guides/coding_guidelines.md'
    - 'guides/git-hooks.md'
    - 'guides/other_teams.md'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  #- stella.tilde2
  #- stella.wikilinks

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/naoteamhumboldt
    - icon: fontawesome/brands/github
      link: https://github.com/BerlinUnited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/teamhumboldt