site_name: Berlin United - Documentation
nav:
  - Teamreport:
    - 'index.md'
    - 'introduction.md'
    - 'architecture_intro.md'
    - 'debugging.md'
    - 'vision.md'
    - 'modeling.md'
    - 'motion.md'
    - 'behavior.md'
    - 'bibliography.md'
  - RobotControl In Depth:
    - 'rc/index.md'
  - RobotCup Project:
    - 'robocup_project/index.md'
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  custom_dir: overrides
  features:
    - navigation.sections

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - stella.tilde2
  - stella.wikilinks

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/youtube
      link: https://twitter.com/squidfunk