site_name: Berlin United - Documentation
nav:
  - Teamreport:
    - 'index.md'
    - 'introduction.md'
    - 'architecture_intro.md'
    - 'debugging.md'
    - 'vision.md'
    - 'modeling.md'
    - 'motion.md'
    - 'behavior.md'
    - 'bibliography.md'
  - NaoTH Tools:
    - 'naoth_tools/rc.md'
    - 'naoth_tools/naoscp.md'
    - 'naoth_tools/xabsleditor.md'
    - 'naoth_tools/simspark.md'
    - 'naoth_tools/webots.md'
    - 'naoth_tools/gitlab-ci.md'
  - RoboCup Tools:
    - 'robocup_tools/index.md'
    - 'robocup_tools/game_recording.md'
  - Deep Learning Pipeline:
    - 'deep_learning/index.md'
    - 'deep_learning/cvat.md'
  - Guides:
    - 'guides/coding_guidelines.md'
    - 'guides/git-hooks.md'
    - 'guides/lab-trackingsystem.md'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  custom_dir: overrides
  features:
    - navigation.sections

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  #- stella.tilde2
  #- stella.wikilinks

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/naoteamhumboldt
    - icon: fontawesome/brands/github
      link: https://github.com/BerlinUnited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/teamhumboldt